# Generated by Django 3.1.1 on 2020-09-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0003_posts_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
